---
title: "Cleaning"
author: "Elsa Heywood"
date: '2022-12-06'
output: html_document
---

#install packages and load them
library(palmerpenguins)
library(ggplot2)
library(janitor)
library(dplyr)

#look at the data- good to provide the raw data for reproducibility. you start with measurements, then get raw data abd clean it up then when you have the clean data you can do analysis code and then either statistics or visualisations and figure
head(penguins_raw)

#one problem is the column names, lets look at them
names(penguins_raw)

#preserving raw data
write.csv(penguins_raw, "data_raw/penguins_raw.csv")


#changing the raw data so we can clean it
penguins_raw <-select(penguins_raw,-starts_with("delta"))
penguins_raw <-select(penguins_raw,-Comments)
names(penguins_raw)

#note- overwriting causes issues so create a new variable name
penguins_raw <- read.csv("data_raw/penguins_raw.csv")
penguins_clean <-select(penguins_raw,-starts_with("delta"))
penguins_clean <-select(penguins_clean,-"Comments")

#start a pipe
penguins_raw <- read.csv("data_raw/penguins_raw.csv")
names(penguins_raw)
penguins_clean <- penguins_raw %>%
  select(-starts_with("delta")) %>%
  select(-Comments) %>%
clean_names()
names(penguins_clean)

#save penguins clean
write.csv(penguins_clean, "data_raw/penguins_clean.csv")

#a better way of piping is making a function, can call the outputs and inputs anything, take the function (clean names) and get the output
cleaning <- function(penguins_raw){
  penguins_raw %>%
    clean_names()
}
#nothing happened so call the function something
names(penguins_raw)
penguins_now_clean <- cleaning(penguins_raw)
names(penguins_raw)
head(penguins_raw)

#another function to take out missing data
remove_empty_flipper_length <- function(data_clean){
  data_clean %>%
    filter(!is.na(flipper_length_mm)) %>%
    select(species, flipper_length_mm)
}

#save the cleaned data
write.csv(penguins_now_clean, "data_clean/penguins_clean.csv")

#you can clean it in one step using the function
penguins_clean <- cleaning(penguins_raw)
head(penguins_clean)

